stages:
  - build
  - deploy
  

build_images:
    stage: build
    image: docker:26.0.0-dind

    services:
      - docker:26.0.0-dind


    variables:
      DOCKER_TLS_CERTDIR: "/certs"

    before_script:
      docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    
    script:
      - docker build -t lucasruchel/projeto1-backend backend/.
      - docker build -t lucasruchel/projeto1-db database/.
      - docker build -t lucasruchel/projeto1-frontend frontend/.
      - docker push lucasruchel/projeto1-backend
      - docker push lucasruchel/projeto1-db
      - docker push lucasruchel/projeto1-frontend

apply_tok8s:
    stage: deploy
    before_script:
      - chmod 400 $SSH_KEY
    script:
      - scp -o StrictHostKeyChecking=no -i $SSH_KEY script.sh lucas@$SSH_HOST:~/
      - chmod +x script.sh
      - ./script.sh

