stages:
  - build
  

build_images:
    stage: build
    image: docker:24.0.0-dind

    variables:
      DOCKER_TLS_CERTDIR: "/certs"

    before_script:
      docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    
    script:
      - docker build -t lucasruchel/projeto1-backend backend/.
      - docker build -t lucasruchel/projeto1-db database/.
      - docker build -t lucasruchel/projeto1-frontend frontend/.
      - docker push lucasruchel/projeto1-backend
      - docker push lucasruchel/projeto1-db
      - docker push lucasruchel/projeto1-frontend

